routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\FormController;
use App\Http\Controllers\FormDataController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TypeDataController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AlgoritmController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('auth.login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    //Route::get('/formulir', [FormController::class, 'index'])->name('formulir');
    //Route::get('/formulir/create', [FormController::class, 'create']);

    // Route::get('/jenis-barang', function() {
    //     return view('type-item');
    // })->name('kategori');

    Route::get('/algorithms', [AlgoritmController::class, 'one'])->name('apriori');

    //Tab Purchase Order
    Route::prefix('formulir')->name('formulir.')->group(function () {
        Route::get('/', [FormController::class, 'index'])->name('index');
        Route::get('/create', [FormController::class, 'create'])->name('create');
        Route::get('/show/{id}', [FormController::class, 'show'])->name('show');
        Route::post('/store/', [FormController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [FormController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [FormController::class, 'update'])->name('update');

        Route::get('/approval/{id}', [FormController::class, 'editdirector'])->name('approval');
        Route::put('/approvalacc/{id}', [FormController::class, 'updatedirector'])->name('approvalacc');
        Route::get('/funds/{id}', [FormController::class, 'editfincance'])->name('funds');
        Route::put('/fundsacc/{id}', [FormController::class, 'updatefinance'])->name('fundsacc');

        Route::get('/delete/{id}', [FormController::class, 'destroy'])->name('delete');
        //Item Barang Relasi Purchase order
        Route::prefix('{id}/item')->name('item.')->group(function ($id) {
            Route::get('/', [FormDataController::class, 'index'])->name('index');
            Route::get('/create', [FormDataController::class, 'create'])->name('create');
            Route::post('/store', [FormDataController::class, 'store'])->name('store');
            //Route::get('/show/{item_id}', [FormDataController::class, 'show'])->name('show');
            //Route::put('/update/{item_id}', [FormDataController::class, 'update'])->name('update');
            Route::get('/delete/{item_id}', [FormDataController::class, 'destroy'])->name('delete');
        });
    });

    //Kategori barang
    Route::prefix('kategori')->name('kategori.')->group(function () {
        Route::get('/', [TypeDataController::class, 'index'])->name('index');
        Route::get('/create', [TypeDataController::class, 'create'])->name('create');
        Route::get('/show/{id}', [TypeDataController::class, 'show'])->name('show');
        Route::post('/store/', [TypeDataController::class, 'store'])->name('store');
        Route::put('/update/{id}', [TypeDataController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [TypeDataController::class, 'destroy'])->name('delete');
    });

    //Tab Supplier
    Route::prefix('pemasok')->name('pemasok.')->group(function () {
        Route::get('/', [SupplierController::class, 'index'])->name('index');
        Route::get('/create', [SupplierController::class, 'create'])->name('create');
        Route::get('/show/{id}', [SupplierController::class, 'show'])->name('show');
        Route::post('/store/', [SupplierController::class, 'store'])->name('store');
        Route::put('/update/{id}', [SupplierController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [SupplierController::class, 'destroy'])->name('delete');
    });
    
    //Tab Karyawan
    Route::prefix('karyawan')->name('karyawan.')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/create', [UserController::class, 'create'])->name('create');
        Route::get('/store', [UserController::class, 'store'])->name('store');
        //Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('delete');
    });
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/employee.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Karyawan') }}
        </h2>
    </x-slot>

    {{-- Style Table --}}
    @push('style')
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    <style>
		
		/*Overrides for Tailwind CSS */
		
		/*Form fields*/
		.dataTables_wrapper select,
		.dataTables_wrapper .dataTables_filter input {
			color: #4a5568; 			/*text-gray-700*/
			padding-left: 1rem; 		/*pl-4*/
			padding-right: 1rem; 		/*pl-4*/
			padding-top: .5rem; 		/*pl-2*/
			padding-bottom: .5rem; 		/*pl-2*/
			line-height: 1.25; 			/*leading-tight*/
			border-width: 2px; 			/*border-2*/
			border-radius: .25rem; 		
			border-color: #edf2f7; 		/*border-gray-200*/
			background-color: #edf2f7; 	/*bg-gray-200*/
		}

		/*Row Hover*/
		table.dataTable.hover tbody tr:hover, table.dataTable.display tbody tr:hover {
			background-color: #ebf4ff;	/*bg-indigo-100*/
		}
		
		/*Pagination Buttons*/
		.dataTables_wrapper .dataTables_paginate .paginate_button		{
			font-weight: 700;				/*font-bold*/
			border-radius: .25rem;			/*rounded*/
			border: 1px solid transparent;	/*border border-transparent*/
		}
		
		/*Pagination Buttons - Current selected */
		.dataTables_wrapper .dataTables_paginate .paginate_button.current	{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06); 	/*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}

		/*Pagination Buttons - Hover */
		.dataTables_wrapper .dataTables_paginate .paginate_button:hover		{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);	 /*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}
		
		/*Add padding to bottom border */
		table.dataTable.no-footer {
			border-bottom: 1px solid #e2e8f0;	/*border-b-1 border-gray-300*/
			margin-top: 0.75em;
			margin-bottom: 0.75em;
		}
		
		/*Change colour of responsive icon*/
		table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before, table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
			background-color: #667eea !important; /*bg-indigo-500*/
		}
		
      </style>
    @endpush

    <div class="py-10">
        <div class="w-full mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg border-lg border">
                <div class="w-full p-10 bg-white rounded shadow-xl">
                    <div class="flex justify-between my-5">
                        <p class="text-xl pb-3 flex items-center">
                            <i class="fas fa-list mr-3"></i> Daftar Karyawan
                        </p>
                        <div class="">
                            <a href="{{ route('karyawan.create') }}" class="px-4 py-2 text-white font-light tracking-wider focus:outline-none rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">Tambah Data</a>
                        </div>
                    </div>

                    <div class="p-8 mt-6 lg:mt-0 rounded shadow bg-white overflow-auto rounded-lg border border-2 border-gray-200">
                        <table id="tabledata" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                            <thead>
                                <tr>
                                    <th data-priority="1" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">No</th>
                                    <th data-priority="2" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Nama Karyawan</th>
                                    <th data-priority="3" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Jabatan</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no=1; ?>
                                @foreach ($user as $data)
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $no++ }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $data->name }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $data->role->name }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">
                                         {{-- <div class="inline-block mr-2 mt-2">
                                            <button type="button" class="focus:outline-none text-white py-2 px-4 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg">Hapus</button>
                                         </div> --}}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('script')
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script>
		$(document).ready(function() {
			var table = $('#tabledata').DataTable( {
					responsive: true
				} )
				.columns.adjust()
				.responsive.recalc();
		} );
	</script>
    @endpush
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/supplier.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Pemasok Barang') }}
        </h2>
    </x-slot>

    {{-- Style Table --}}
    @push('style')
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    <style>
		
		/*Overrides for Tailwind CSS */
		
		/*Form fields*/
		.dataTables_wrapper select,
		.dataTables_wrapper .dataTables_filter input {
			color: #4a5568; 			/*text-gray-700*/
			padding-left: 1rem; 		/*pl-4*/
			padding-right: 1rem; 		/*pl-4*/
			padding-top: .5rem; 		/*pl-2*/
			padding-bottom: .5rem; 		/*pl-2*/
			line-height: 1.25; 			/*leading-tight*/
			border-width: 2px; 			/*border-2*/
			border-radius: .25rem; 		
			border-color: #edf2f7; 		/*border-gray-200*/
			background-color: #edf2f7; 	/*bg-gray-200*/
		}

		/*Row Hover*/
		table.dataTable.hover tbody tr:hover, table.dataTable.display tbody tr:hover {
			background-color: #ebf4ff;	/*bg-indigo-100*/
		}
		
		/*Pagination Buttons*/
		.dataTables_wrapper .dataTables_paginate .paginate_button		{
			font-weight: 700;				/*font-bold*/
			border-radius: .25rem;			/*rounded*/
			border: 1px solid transparent;	/*border border-transparent*/
		}
		
		/*Pagination Buttons - Current selected */
		.dataTables_wrapper .dataTables_paginate .paginate_button.current	{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06); 	/*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}

		/*Pagination Buttons - Hover */
		.dataTables_wrapper .dataTables_paginate .paginate_button:hover		{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);	 /*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}
		
		/*Add padding to bottom border */
		table.dataTable.no-footer {
			border-bottom: 1px solid #e2e8f0;	/*border-b-1 border-gray-300*/
			margin-top: 0.75em;
			margin-bottom: 0.75em;
		}
		
		/*Change colour of responsive icon*/
		table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before, table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
			background-color: #667eea !important; /*bg-indigo-500*/
		}
		
      </style>
    @endpush

    <div class="py-10">
        <div class="w-full mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg border-lg border">
                <div class="w-full p-10 bg-white rounded shadow-xl">
                    <div class="flex justify-between my-5">
                        <p class="text-xl pb-3 flex items-center">
                            <i class="fas fa-list mr-3"></i> Daftar Pemasok Barang
                        </p>
                        <div class="">
                            <a href="{{ route('pemasok.create') }}" class="px-4 py-2 text-white font-light tracking-wider focus:outline-none rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">Tambah Data</a>
                        </div>
                    </div>
                    
                    <div class="p-8 mt-6 lg:mt-0 rounded shadow bg-white overflow-auto rounded-lg border border-2 border-gray-200">
                        <table id="tabledata" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                            <thead>
                                <tr>
                                    <th data-priority="1" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">No</th>
                                    <th data-priority="2" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Nama Pemasok</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no=1; ?>
                                @foreach ($suppliers as $data)
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $no++ }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $data->supplier_name }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">
                                        <div class="inline-block mr-2 mt-2">
                                            <a href="{{ route('pemasok.show', $data->id) }}"  class="focus:outline-none text-white py-2 px-4 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg">Lihat</a>
                                        </div>
                                        <div class="inline-block mr-2 mt-2">
                                            <!-- modal div -->
                                            <div x-data="{ open: false }">
                                                <button type="button" class="focus:outline-none text-white py-2 px-4 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg" @click="open = true">Hapus</button>
                                                <!-- Dialog (full screen) -->
                                                <div class="absolute top-0 left-0 flex items-center justify-center w-full h-full" style="background-color: rgba(0,0,0,.5);" x-show="open"  >
                                                <!-- A basic modal dialog with title, body and one button to close -->
                                                    <div class="h-auto p-4 mx-2 text-left bg-white rounded shadow-xl md:max-w-xl md:p-6 lg:p-8 md:mx-0" @click.away="open = false">
                                                        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                                            <h3 class="text-lg font-high leading-6 text-black">
                                                                Perhatian !!
                                                            </h3>
                                                
                                                            <div class="mt-2">
                                                                <p class="text-sm leading-5 text-gray-500">
                                                                Apakah anda yakin ingin menghapus data ini ?
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <!-- One big close button.  --->
                                                        <div class="mt-5 sm:mt-6">
                                                            <span class="flex w-full rounded-md shadow-sm">
                                                                <button @click="open = false" class="inline-flex justify-center w-full mx-5 px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-700">
                                                                Tidak
                                                                </button>
                                                                <a href="{{ route('pemasok.delete', $data->id) }}" class="inline-flex justify-center w-full mx-5 px-4 py-2 text-white bg-red-500 rounded hover:bg-red-700">
                                                                    Ya
                                                                </a>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('script')
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script>
		$(document).ready(function() {
			var table = $('#tabledata').DataTable( {
					responsive: true
				} )
				.columns.adjust()
				.responsive.recalc();
		} );
	</script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
    @endpush
</x-app-layout>

resources/views/type-item.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Tipe Barang') }}
        </h2>
    </x-slot>

    {{-- Style Table --}}
    @push('style')
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
	<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
    <style>
		
		/*Overrides for Tailwind CSS */
		
		/*Form fields*/
		.dataTables_wrapper select,
		.dataTables_wrapper .dataTables_filter input {
			color: #4a5568; 			/*text-gray-700*/
			padding-left: 1rem; 		/*pl-4*/
			padding-right: 1rem; 		/*pl-4*/
			padding-top: .5rem; 		/*pl-2*/
			padding-bottom: .5rem; 		/*pl-2*/
			line-height: 1.25; 			/*leading-tight*/
			border-width: 2px; 			/*border-2*/
			border-radius: .25rem; 		
			border-color: #edf2f7; 		/*border-gray-200*/
			background-color: #edf2f7; 	/*bg-gray-200*/
		}

		/*Row Hover*/
		table.dataTable.hover tbody tr:hover, table.dataTable.display tbody tr:hover {
			background-color: #ebf4ff;	/*bg-indigo-100*/
		}
		
		/*Pagination Buttons*/
		.dataTables_wrapper .dataTables_paginate .paginate_button		{
			font-weight: 700;				/*font-bold*/
			border-radius: .25rem;			/*rounded*/
			border: 1px solid transparent;	/*border border-transparent*/
		}
		
		/*Pagination Buttons - Current selected */
		.dataTables_wrapper .dataTables_paginate .paginate_button.current	{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06); 	/*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}

		/*Pagination Buttons - Hover */
		.dataTables_wrapper .dataTables_paginate .paginate_button:hover		{
			color: #fff !important;				/*text-white*/
			box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);	 /*shadow*/
			font-weight: 700;					/*font-bold*/
			border-radius: .25rem;				/*rounded*/
			background: #667eea !important;		/*bg-indigo-500*/
			border: 1px solid transparent;		/*border border-transparent*/
		}
		
		/*Add padding to bottom border */
		table.dataTable.no-footer {
			border-bottom: 1px solid #e2e8f0;	/*border-b-1 border-gray-300*/
			margin-top: 0.75em;
			margin-bottom: 0.75em;
		}
		
		/*Change colour of responsive icon*/
		table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before, table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
			background-color: #667eea !important; /*bg-indigo-500*/
		}
		
      </style>
    @endpush

    <div class="py-10">
        <div class="w-full mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg border-lg border">
                <div class="w-full p-10 bg-white rounded shadow-xl">
                    <div class="flex justify-between my-5">
                        <p class="text-xl pb-3 flex items-center">
                            <i class="fas fa-list mr-3"></i> Daftar Tipe Jenis Barang
                        </p>
                        <div class="">
                            <a href="{{ route('kategori.create') }}" class="px-4 py-2 text-white font-light tracking-wider focus:outline-none rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">Tambah Data</a>
                        </div>
                    </div>
                    
                    <div class="p-8 mt-6 lg:mt-0 rounded shadow bg-white overflow-auto rounded-lg border border-2 border-gray-200">
                        <table id="tabledata" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                            <thead>
                                <tr>
                                    <th data-priority="1" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">No</th>
                                    <th data-priority="2" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Nama Tipe Barang</th>
                                    <th data-priority="3" class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Deskripsi</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no=1; ?>
                                @foreach ($category as $data)
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $no++ }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $data->type_name }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ $data->description }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">
                                        <div class="inline-block mr-2 mt-2">
                                           <a href="{{ route('kategori.show', $data->id) }}" type="button" class="focus:outline-none text-white py-2 px-4 rounded-md bg-yellow-500 hover:bg-yellow-600 hover:shadow-lg">Ubah</a>
                                        </div>
                                        <div class="inline-block mr-2 mt-2">
                                            <!-- modal div -->
                                            <div x-data="{ open: false }">
                                                <button type="button" class="focus:outline-none text-white py-2 px-4 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg" @click="open = true">Hapus</button>
                                                <!-- Dialog (full screen) -->
                                                <div class="absolute top-0 left-0 flex items-center justify-center w-full h-full" style="background-color: rgba(0,0,0,.5);" x-show="open"  >
                                                <!-- A basic modal dialog with title, body and one button to close -->
                                                    <div class="h-auto p-4 mx-2 text-left bg-white rounded shadow-xl md:max-w-xl md:p-6 lg:p-8 md:mx-0" @click.away="open = false">
                                                        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                                            <h3 class="text-lg font-high leading-6 text-black">
                                                                Perhatian !!
                                                            </h3>
                                                
                                                            <div class="mt-2">
                                                                <p class="text-sm leading-5 text-gray-500">
                                                                Apakah anda yakin ingin menghapus data ini ?
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <!-- One big close button.  --->
                                                        <div class="mt-5 sm:mt-6">
                                                            <span class="flex w-full rounded-md shadow-sm">
                                                                <button @click="open = false" class="inline-flex justify-center w-full mx-5 px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-700">
                                                                Tidak
                                                                </button>
                                                                <a href="{{ route('kategori.delete', $data->id) }}" class="inline-flex justify-center w-full mx-5 px-4 py-2 text-white bg-red-500 rounded hover:bg-red-700">
                                                                    Ya
                                                                </a>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                   </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('script')
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
	<script>
		$(document).ready(function() {
			var table = $('#tabledata').DataTable( {
					responsive: true
				} )
				.columns.adjust()
				.responsive.recalc();
		} );
	</script>
	<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
    @endpush
</x-app-layout>